### ISSUE TITLE
Modal for project "Listed" incorrectly linked

### ISSUE THREAD

**Issue by timtheguy** [WilhelmWillie/wilhelmwillie.github.io#1]
The "_See Project_" button on the "Listed" modal links to the slide deck for "kit" instead of the project page for "Listed".

![screen shot 2017-02-17 at 5 01 48 pm](https://cloud.githubusercontent.com/assets/9803215/23084924/ce71b1d0-f532-11e6-99db-ad5c7d8fe28a.png)

**Comment by WilhelmWillie** [comment]
Fixed!
